---
- type: replace
  path: /name=stemcell/value
  value:
    sha1: 765861344eab1faaa10ac65967dadcb6edf8c0db
    url: https://storage.googleapis.com/bosh-core-stemcells/1.918/bosh-stemcell-1.918-warden-boshlite-ubuntu-jammy-go_agent.tgz
